### ISSUE TITLE
PrEP Screening test schedule

### ISSUE THREAD

**Issue by victormanase** [SoftmedTanzania/opensrp-client-chw-kvp#20]
1. HTS

- [ ] at first vist
- [ ] at 28 days
- [ ] after every 3 month 

2. Cretinine test

- [ ] at first vist
- [ ] every 6 month
- [ ] if a client cretinne clearence is less than 60 the application should alert the client to repeat the test after 14 days 

3. HBV & HCV

- [ ] at first vist
- [ ] every 6 month

**Comment by Kasika-S** [comment]
HTS Schedule has been reserved as backlog pending further discussion
